### ISSUE TITLE
Ping climbs endlessy until error

### ISSUE THREAD

**Issue by LickRish** [FirstGearGames/FishySteamworks#2]
when rapidly sending RPCs the clients ping will begin to rise endlessly. Eventually an error "k_EResultLimitExceeded" is produced on the server. I'm using P2P and steam app ID 480. I would be happy to submit more info to help narrow this down.

**Comment by FirstGearGames** [comment]
Doesn't seem like a bug. Steam might be cutting you off for excessive messages.
https://partner.steamgames.com/doc/api/steam_api

**Comment by LickRish** [comment]
im sending 4 nearly full packets every server tick (30 ticks a second)... do you think that is too much data for steam? It seemed to work fine using tugboat 😥

**Comment by FirstGearGames** [comment]
It's not a problem with the transport so much that it's actually Steam limiting you. They don't appreciate you blowing up their servers.

**Comment by LickRish** [comment]
thats fair... thanks
