### ISSUE TITLE
Please add support for old steamNetworking!

### ISSUE THREAD

**Issue by 15so42** [FirstGearGames/FishySteamworks#7]
I researched and asked a lot of people for a few weeks and finally found out the reason why players in China couldn't connect to each other, SteamnetSockets wouldn't work well in China because of all the restrictions on the Chinese network. However, the old version of SteamNetworking is not affected, and Chinese players can normally connect with each other using the old version of SteamNetworking, so I hope to add support for the old version of Steamnetworking!
please!!!

**Comment by FirstGearGames** [comment]
There's no plans to add old support at this time, sorry.
